### ISSUE TITLE
Image not being recognized

### ISSUE THREAD

**Issue by georgemty** [alpharaoh/AmongUsBot#2] opened 2020-09-11 17:35 UTC
Hello! I have an issue with the image recognition. Whenever I try puting the example image or the game itself, the bot doesn't recognizes neither so there's no muting/unmuting but if I try the command ".mute" / ".unmute" it works and mutes/unmutes everyone on the voice chat. I went back to config and run config.py to see if there was a problem with the image recognition but it seems everything's okay. Whenever I run the config.py the impostor/crewmate text fits perfectly on the rectangunlar window that pops upon running config.py.

**Comment by denverquane** [comment] 2020-09-11 18:28
I noticed when testing a lot yesterday that the start.py and test.py scripts don't respect the config.py values the same (aka the window displayed by test.py was different than the real window when the discord bot runs). I have a Pull Request out [here](https://github.com/alpharaoh/AmongUsBot/pull/3) (you can download my repository there and mess with the config.py until it works for you if you like), but hopefully that would be merged soon to help alleviate some of the problems.

In my case, it was largely caused by running a 2560x1440p resolution; what about you?

**Comment by georgemty** [comment] 2020-09-11 18:33
I've been playing with the config all this morning and it seems to be a problem with the adjust_x and adjust_y values and not with the resolution itself since I have the recommended resolution you set which is 1920x1080. Will continue to play with the config file and continue to make tests to see if it works properly. Thanks for the quick response btw! :))

**Comment by denverquane** [comment] 2020-09-11 18:38
For sure! To clarify a little bit, I noticed that even at 1080p the problem is still around; I think the offsets might help, but you can also mess with the decimal values [here](https://github.com/alpharaoh/AmongUsBot/blob/master/modules/module_grabscreen.py#L18) and [here](https://github.com/alpharaoh/AmongUsBot/blob/master/modules/module_grabscreen.py#L38) (that's what my pull request addresses). I even think those lines should be entirely reversed from my testing... the "discussion" capture window is really large, and the "ending" capture window is small, but when playing the game, you can see how those should be swapped...

Anyways, good luck!

**Comment by alpharaoh** [comment] 2020-09-11 18:41
Yeh, so after inspecting my code seems like the res in the config didn't actually affect any code and other things aswell. I've got an update that tackles these issues that im releasing soon! Thanks everyone for your interest in my project! @denverquane @georgemty @CAP1Sup

**Comment by georgemty** [comment] 2020-09-11 18:46
I'll play with those values as well, thanks for the tip! I hope I can succeed and if not I'll wait for your next version and just make a pull request hehe. Thanks for the help!! :))

**Comment by georgemty** [comment] 2020-09-11 18:48
Thank you so much for the reply @alpharaoh ! can't wait for the next update, you did an amazing job on this bot, hands down to your great work using python!! 💯

**Closed as completed** 2020-09-16 16:23 UTC
